Repository 12-Pair-Programming/Dang-il, pull requests merged in 2024-05, with the labels that each got.

#123 [FEAT] 알바 신청 내역 & 공고 신청자 목록 테이블 데이터 연결
  features/MyProfileInfo/.keep
  features/MyProfileInfo/FindNotice.tsx
  features/MyProfileInfo/FindProfile.tsx
  features/MyShopInfo/FindNotice.tsx
  features/MyShopInfo/FindShop.tsx
  features/NoticeInfo/EmployeeList.tsx
  features/NoticeList/AllNotice.tsx
  pages/noticeInfo.tsx
  pages/registMyShop.tsx
  shared/.keep
  shared/@common/.keep
  shared/@common/api/applicationAPI.ts
  shared/@common/ui/Nav/NavigationBar.tsx
  shared/@common/ui/Nav/navModal/NavModal.tsx
  shared/@common/ui/Nav/navModal/navModalMessage/NavModalMessage.tsx
  shared/@common/ui/Table/Table.tsx
  shared/@common/ui/Table/TableBody.tsx
  shared/@common/ui/Table/TableButton.tsx
  shared/@common/ui/Table/api/useTableData.tsx
  shared/@common/ui/Table/test/tableTest.ts
  shared/utils/axiosInstance.ts
Labels: feat, fix

#127 116 feat 공고 상세 지난공고 표시 카드컴포넌트 링크
  features/NoticeInfo/EmployeeList.tsx
  features/NoticeInfo/NoticeShopInfo.tsx
  features/NoticeInfo/RecentNotices.tsx
  pages/noticeInfo.tsx
  shared/@common/notice/ui/Card.tsx
  shared/@common/notice/ui/CardImage.tsx
  shared/@common/notice/ui/NoticePayInfo.tsx
  shared/@common/notice/ui/NoticeTimeAndLocation.tsx
  shared/@common/notice/utils/isPastNotice.ts
Labels: style, refactor, fix

#126 [FEAT] 리드미 제작
  README.md
Labels: feat

#129 [STYLE] NoticeList 반응형 수정 / 로딩 처리
  features/.keep
  features/EditMyProfile/.keep
  features/EditMyShop/.keep
  features/EditMyShop/EditingMyShop.tsx
  features/Login/.keep
  features/MyShopInfo/.keep
  features/NoticeList/AllNotice.tsx
  features/NoticeList/CustomNotice.tsx
  features/NoticeRegist/.keep
  features/Regist/.keep
  features/RegistMyProfile/.keep
  features/RegistMyShop/.keep
  package-lock.json
  package.json
  pages/_app.tsx
  pages/noticeInfo.tsx
  public/favicon.ico
  shared/@common/api/shopAPI.ts
  shared/@common/api/userAPI.ts
  shared/@common/auth/api/.keep
  shared/@common/auth/hooks/.keep
  shared/@common/auth/types/.keep
  shared/@common/auth/ui/.keep
  shared/@common/auth/utils/.keep
  shared/@common/myProfile/api/.keep
  shared/@common/myProfile/hooks/.keep
  shared/@common/myProfile/types/.keep
  shared/@common/myProfile/ui/.keep
  shared/@common/myProfile/utils/.keep
  shared/@common/myShop/api/.keep
  shared/@common/myShop/hooks/.keep
  shared/@common/myShop/types/.keep
  shared/@common/myShop/ui/.keep
  shared/@common/myShop/utils/.keep
  shared/@common/notice/.keep
  shared/@common/notice/hooks/.keep
  shared/@common/notice/types/.keep
  shared/@common/notice/ui/.keep
  shared/@common/ui/Button/.keep
  shared/@common/ui/Card/.keep
  shared/@common/ui/Dropdown/.keep
  shared/@common/ui/Loading.tsx
  shared/@common/ui/Modal/.keep
  shared/@common/ui/Nav/.keep
  shared/@common/ui/Table/Table.tsx
Labels: style, fix

#134 [FIX] 로그인과 회원가입 페이지의 오류 수정 및 주석 제거
  features/Login/LoginBody.tsx
  features/Regist/RegistBody.tsx
  shared/@common/auth/hooks/useCheckUserData.tsx
  shared/@common/ui/Button/Button.tsx
Labels: refactor, fix

#135 [FIX] 공고 상세 버튼 오동작 수정
  features/NoticeInfo/NoticeShopInfo.tsx
Labels: bug

#136 [REFACTOR] 주석 제거 / any 제거 / console 제거 / axiosInstance 위치 변경
  features/MyShopInfo/FindNotice.tsx
  features/MyShopInfo/FindShop.tsx
  features/NoticeInfo/NoticeShopInfo.tsx
  features/NoticeList/AllNotice.tsx
  features/NoticeList/CustomNotice.tsx
  pages/_document.tsx
  pages/noticeInfo.tsx
  shared/@common/api/alertAPI.ts
  shared/@common/api/applicationAPI.ts
  shared/@common/api/authenticationAPI.ts
  shared/@common/api/axiosInstance.ts
  shared/@common/api/noticeAPI.ts
  shared/@common/api/shopAPI.ts
  shared/@common/api/userAPI.ts
  shared/@common/ui/Table/TableBody.tsx
Labels: refactor
